In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
K = 3

In [3]:
matriz_scores = pd.read_csv('../datasets/matriz_produto_usuario.csv')

In [4]:
matriz_scores

,id_produto,U_0,U_1,U_10,U_100,U_101,U_102,U_103,U_104,U_105,...,U_99,U_990,U_991,U_992,U_993,U_994,U_995,U_997,U_998,U_999
0,P_0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
1,P_1,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
2,P_10,0.0,0.00000,0.0,0.0,0.0,0.0,6.331518,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
3,P_11,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
4,P_12,0.0,2.42357,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,P_95,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,1.994154,0.0,...,0.000000,0.0,0.0,0.0,0.0,3.245922,0.0,0.000000,0.0,0.0
96,P_96,0.0,0.00000,0.0,1.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
97,P_97,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,2.385233,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,1.556020,0.0,0.0
98,P_98,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,2.762232,0.0,0.0,0.0,0.0,0.000000,0.0,7.914848,0.0,0.0
99,P_99,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,6.814755,0.0,0.0

In [5]:
# Extrai os id_produto como um array
# Será usado para nomear linhas e colunas da matriz de similaridade
ids_produtos = matriz_scores['id_produto'].values

# Converte o dataframe, sem acoluna de id_produto, em um array numpy
X_scores = matriz_scores.drop(columns='id_produto').to_numpy(dtype=float)

# Cálculo da similaridade cosseno
# O resultado é uma matriz quadrada, com cada valor remetendo a 2 produtos
# As dimensões para calcular as "distâncias" são os usuários
    # Se houvesse apenas 3 usuários, seria possível visualizar cada produto como um ponto em um cubo, com sua posição determinada pelo score de cada um desses três usuários
    # Mas há 1000 usuários, então isso não é visualizável da mesma forma
similaridade_cosseno_produtos = cosine_similarity(X_scores)

# Retornando o resultado para um dataframe legível
similaridade_item_item = pd.DataFrame(
    similaridade_cosseno_produtos,
    index=ids_produtos,
    columns=ids_produtos
)

# Arredondamento para fins de apresentação e eventual poupança de memória
similaridade_item_item = similaridade_item_item.round(6)

In [6]:
similaridade_item_item.to_csv('../dados_sinteticos/dados_tratatos/similaridade_item_item.csv')

In [7]:
similaridade_item_item

,P_0,P_1,P_10,P_11,P_12,P_13,P_14,P_15,P_16,P_17,...,P_90,P_91,P_92,P_93,P_94,P_95,P_96,P_97,P_98,P_99
P_0,1.000000,0.000000,0.044277,0.170036,0.013053,0.000000,0.000000,0.000000,0.051897,0.062071,...,0.000000,0.000000,0.010633,0.0,0.000000,0.000000,0.149624,0.000000,0.038132,0.005890
P_1,0.000000,1.000000,0.000000,0.000000,0.096727,0.000000,0.009647,0.039448,0.000000,0.000000,...,0.000000,0.084355,0.000000,0.0,0.050323,0.019188,0.015019,0.086442,0.101429,0.082315
P_10,0.044277,0.000000,1.000000,0.044079,0.095343,0.000000,0.000000,0.000000,0.000000,0.020372,...,0.027444,0.000000,0.074826,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
P_11,0.170036,0.000000,0.044079,1.000000,0.000000,0.000000,0.000000,0.000000,0.050261,0.036552,...,0.066543,0.000000,0.051615,0.0,0.000000,0.000000,0.016058,0.000000,0.000000,0.000000
P_12,0.013053,0.096727,0.095343,0.000000,1.000000,0.024804,0.000000,0.000000,0.000000,0.015453,...,0.000000,0.000000,0.084138,0.0,0.000000,0.085973,0.005064,0.000000,0.076714,0.006874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P_95,0.000000,0.019188,0.000000,0.000000,0.085973,0.000000,0.000000,0.033964,0.000000,0.000000,...,0.000000,0.130265,0.000000,0.0,0.000000,1.000000,0.000000,0.024046,0.039570,0.000000
P_96,0.149624,0.015019,0.000000,0.016058,0.005064,0.100628,0.006149,0.005047,0.095299,0.003110,...,0.000000,0.000000,0.000000,0.0,0.093825,0.000000,1.000000,0.013080,0.048807,0.080525
P_97,0.000000,0.086442,0.000000,0.000000,0.000000,0.043420,0.020932,0.028305,0.015812,0.000000,...,0.000000,0.090141,0.000000,0.0,0.081116,0.024046,0.013080,1.000000,0.019905,0.019464
P_98,0.038132,0.101429,0.000000,0.000000,0.076714,0.177726,0.000000,0.000000,0.045002,0.000000,...,0.000000,0.000000,0.000000,0.0,0.132800,0.039570,0.048807,0.019905,1.000000,0.150915
P_99,0.005890,0.082315,0.000000,0.000000,0.006874,0.195219,0.018726,0.000000,0.086349,0.000000,...,0.000000,0.000000,0.000000,0.0,0.204050,0.000000,0.080525,0.019464,0.150915,1.000000

In [8]:
# Impressão das três maiores similaridades por item
for col in similaridade_item_item.columns:
    print(f'  {col}')
    print(similaridade_item_item[similaridade_item_item.index != col][col].nlargest(K))

  P_0
P_40    0.209163
P_54    0.175689
P_32    0.171062
Name: P_0, dtype: float64
  P_1
P_4     0.318086
P_27    0.296025
P_58    0.231695
Name: P_1, dtype: float64
  P_10
P_5     0.196341
P_41    0.195248
P_77    0.176079
Name: P_10, dtype: float64
  P_11
P_0     0.170036
P_63    0.124796
P_69    0.090959
Name: P_11, dtype: float64
  P_12
P_58    0.255983
P_72    0.206396
P_5     0.173565
Name: P_12, dtype: float64
  P_13
P_64    0.350745
P_60    0.342910
P_50    0.206396
Name: P_13, dtype: float64
  P_14
P_25    0.264175
P_70    0.205193
P_56    0.182821
Name: P_14, dtype: float64
  P_15
P_70    0.158687
P_33    0.149867
P_21    0.136851
Name: P_15, dtype: float64
  P_16
P_2     0.152683
P_8     0.139737
P_48    0.139066
Name: P_16, dtype: float64
  P_17
P_62    0.270076
P_93    0.220194
P_23    0.188949
Name: P_17, dtype: float64
  P_18
P_50    0.275077
P_74    0.266414
P_99    0.247705
Name: P_18, dtype: float64
  P_19
P_72    0.285075
P_95    0.228813
P_27    0.196066
Name: P_19, dtype: float64
  P_2
P_48    0.186217
P_54    0.183197
P_57    0.178288
Name: P_2, dtype: float64
  P_20
P_93    0.195971
P_21    0.186807
P_89    0.154061
Name: P_20, dtype: float64
  P_21
P_44    0.257996
P_42    0.247141
P_91    0.231904
Name: P_21, dtype: float64
  P_22
P_79    0.325903
P_69    0.190168
P_8     0.180634
Name: P_22, dtype: float64
  P_23
P_87    0.210367
P_93    0.202128
P_62    0.200832
Name: P_23, dtype: float64
  P_24
P_40    0.211963
P_29    0.199802
P_8     0.193894
Name: P_24, dtype: float64
  P_25
P_70    0.283596
P_14    0.264175
P_39    0.221654
Name: P_25, dtype: float64
  P_26
P_99    0.158690
P_48    0.147076
P_16    0.115667
Name: P_26, dtype: float64
  P_27
P_1     0.296025
P_73    0.272948
P_80    0.237084
Name: P_27, dtype: float64
  P_28
P_85    0.184126
P_83    0.161286
P_89    0.145256
Name: P_28, dtype: float64
  P_29
P_99    0.258436
P_57    0.225825
P_24    0.199802
Name: P_29, dtype: float64
  P_3
P_68    0.178143
P_77    0.174692
P_29    0.152363
Name: P_3, dtype: float64
  P_30
P_5     0.174541
P_67    0.173117
P_29    0.158072
Name: P_30, dtype: float64
  P_31
P_70    0.190702
P_81    0.146507
P_71    0.133747
Name: P_31, dtype: float64
  P_32
P_0     0.171062
P_54    0.160667
P_24    0.151849
Name: P_32, dtype: float64
  P_33
P_84    0.241923
P_25    0.170365
P_46    0.158792
Name: P_33, dtype: float64
  P_34
P_74    0.241317
P_18    0.208280
P_63    0.197645
Name: P_34, dtype: float64
  P_35
P_4     0.324533
P_74    0.281017
P_36    0.209275
Name: P_35, dtype: float64
  P_36
P_74    0.244302
P_35    0.209275
P_52    0.187794
Name: P_36, dtype: float64
  P_37
P_47    0.258425
P_76    0.169440
P_87    0.168147
Name: P_37, dtype: float64
  P_38
P_88    0.193100
P_8     0.169874
P_57    0.163263
Name: P_38, dtype: float64
  P_39
P_25    0.221654
P_71    0.220210
P_56    0.150941
Name: P_39, dtype: float64
  P_4
P_98    0.391868
P_35    0.324533
P_1     0.318086
Name: P_4, dtype: float64
  P_40
P_67    0.233403
P_54    0.213490
P_24    0.211963
Name: P_40, dtype: float64
  P_41
P_5     0.428768
P_10    0.195248
P_77    0.183126
Name: P_41, dtype: float64
  P_42
P_91    0.336272
P_9     0.276144
P_55    0.255861
Name: P_42, dtype: float64
  P_43
P_93    0.259403
P_53    0.159540
P_20    0.088618
Name: P_43, dtype: float64
  P_44
P_21    0.257996
P_91    0.252350
P_9     0.235074
Name: P_44, dtype: float64
  P_45
P_87    0.206526
P_37    0.155411
P_9     0.154724
Name: P_45, dtype: float64
  P_46
P_21    0.213603
P_49    0.198971
P_83    0.198796
Name: P_46, dtype: float64
  P_47
P_37    0.258425
P_90    0.141183
P_16    0.116630
Name: P_47, dtype: float64
  P_48
P_40    0.202039
P_99    0.192087
P_2     0.186217
Name: P_48, dtype: float64
  P_49
P_68    0.304313
P_44    0.200330
P_46    0.198971
Name: P_49, dtype: float64
  P_5
P_41    0.428768
P_10    0.196341
P_88    0.175277
Name: P_5, dtype: float64
  P_50
P_60    0.283454
P_18    0.275077
P_99    0.230673
Name: P_50, dtype: float64
  P_51
P_42    0.245987
P_21    0.184887
P_85    0.176989
Name: P_51, dtype: float64
  P_52
P_74    0.192358
P_36    0.187794
P_75    0.175471
Name: P_52, dtype: float64
  P_53
P_87    0.248509
P_93    0.190738
P_43    0.159540
Name: P_53, dtype: float64
  P_54
P_67    0.317877
P_40    0.213490
P_2     0.183197
Name: P_54, dtype: float64
  P_55
P_9     0.374795
P_56    0.318574
P_42    0.255861
Name: P_55, dtype: float64
  P_56
P_55    0.318574
P_9     0.281625
P_25    0.192106
Name: P_56, dtype: float64
  P_57
P_82    0.227058
P_29    0.225825
P_2     0.178288
Name: P_57, dtype: float64
  P_58
P_72    0.338454
P_12    0.255983
P_73    0.243435
Name: P_58, dtype: float64
  P_59
P_7     0.257605
P_41    0.180272
P_5     0.165008
Name: P_59, dtype: float64
  P_6
P_83    0.211919
P_9     0.186742
P_46    0.183333
Name: P_6, dtype: float64
  P_60
P_13    0.342910
P_50    0.283454
P_4     0.236488
Name: P_60, dtype: float64
  P_61
P_99    0.151742
P_74    0.147829
P_4     0.142249
Name: P_61, dtype: float64
  P_62
P_93    0.280672
P_17    0.270076
P_23    0.200832
Name: P_62, dtype: float64
  P_63
P_68    0.203023
P_34    0.197645
P_96    0.153885
Name: P_63, dtype: float64
  P_64
P_13    0.350745
P_4     0.248652
P_50    0.205903
Name: P_64, dtype: float64
  P_65
P_76    0.147463
P_52    0.119457
P_63    0.118444
Name: P_65, dtype: float64
  P_66
P_93    0.199017
P_83    0.160323
P_28    0.143568
Name: P_66, dtype: float64
  P_67
P_54    0.317877
P_40    0.233403
P_4     0.207589
Name: P_67, dtype: float64
  P_68
P_49    0.304313
P_72    0.242820
P_63    0.203023
Name: P_68, dtype: float64
  P_69
P_22    0.190168
P_96    0.163825
P_8     0.154629
Name: P_69, dtype: float64
  P_7
P_59    0.257605
P_8     0.211913
P_78    0.194321
Name: P_7, dtype: float64
  P_70
P_25    0.283596
P_14    0.205193
P_31    0.190702
Name: P_70, dtype: float64
  P_71
P_39    0.220210
P_25    0.182429
P_31    0.133747
Name: P_71, dtype: float64
  P_72
P_58    0.338454
P_19    0.285075
P_68    0.242820
Name: P_72, dtype: float64
  P_73
P_27    0.272948
P_58    0.243435
P_49    0.198238
Name: P_73, dtype: float64
  P_74
P_4     0.281088
P_35    0.281017
P_18    0.266414
Name: P_74, dtype: float64
  P_75
P_18    0.233230
P_50    0.197620
P_52    0.175471
Name: P_75, dtype: float64
  P_76
P_37    0.169440
P_65    0.147463
P_56    0.139529
Name: P_76, dtype: float64
  P_77
P_82    0.226758
P_41    0.183126
P_94    0.176411
Name: P_77, dtype: float64
  P_78
P_7     0.194321
P_41    0.177915
P_40    0.166287
Name: P_78, dtype: float64
  P_79
P_22    0.325903
P_94    0.249274
P_96    0.189044
Name: P_79, dtype: float64
  P_8
P_7     0.211913
P_24    0.193894
P_88    0.193742
Name: P_8, dtype: float64
  P_80
P_27    0.237084
P_73    0.168733
P_58    0.162823
Name: P_80, dtype: float64
  P_81
P_87    0.183266
P_31    0.146507
P_25    0.127558
Name: P_81, dtype: float64
  P_82
P_57    0.227058
P_77    0.226758
P_60    0.179190
Name: P_82, dtype: float64
  P_83
P_6     0.211919
P_46    0.198796
P_68    0.182854
Name: P_83, dtype: float64
  P_84
P_33    0.241923
P_6     0.172002
P_25    0.100459
Name: P_84, dtype: float64
  P_85
P_28    0.184126
P_51    0.176989
P_44    0.169914
Name: P_85, dtype: float64
  P_86
P_96    0.165249
P_79    0.161493
P_8     0.151037
Name: P_86, dtype: float64
  P_87
P_53    0.248509
P_23    0.210367
P_45    0.206526
Name: P_87, dtype: float64
  P_88
P_8     0.193742
P_38    0.193100
P_7     0.189654
Name: P_88, dtype: float64
  P_89
P_21    0.188962
P_20    0.154061
P_85    0.150242
Name: P_89, dtype: float64
  P_9
P_55    0.374795
P_56    0.281625
P_42    0.276144
Name: P_9, dtype: float64
  P_90
P_93    0.187910
P_92    0.152530
P_47    0.141183
Name: P_90, dtype: float64
  P_91
P_42    0.336272
P_44    0.252350
P_9     0.246132
Name: P_91, dtype: float64
  P_92
P_62    0.193374
P_41    0.159981
P_90    0.152530
Name: P_92, dtype: float64
  P_93
P_62    0.280672
P_43    0.259403
P_17    0.220194
Name: P_93, dtype: float64
  P_94
P_79    0.249274
P_60    0.218219
P_99    0.204050
Name: P_94, dtype: float64
  P_95
P_19    0.228813
P_21    0.220146
P_44    0.198610
Name: P_95, dtype: float64
  P_96
P_79    0.189044
P_2     0.176746
P_22    0.174611
Name: P_96, dtype: float64
  P_97
P_55    0.163801
P_50    0.133532
P_85    0.132167
Name: P_97, dtype: float64
  P_98
P_4     0.391868
P_60    0.204337
P_64    0.194293
Name: P_98, dtype: float64
  P_99
P_29    0.258436
P_18    0.247705
P_50    0.230673
Name: P_99, dtype: float64